name: AdventOfCode2018.dart

environment:
  sdk: '^3.5.0'
dependencies:
  collection: ^1.19.0
  crypto: ^3.0.3
  either_dart: ^1.0.0
  memoized: ^2.2.6
  petitparser: ^6.0.2
  test: ^1.25.8
dev_dependencies:
  lints: ^4.0.0
